---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  labels:
    chart: podinfo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:master-*
spec:
  chartGitPath: podinfo
  releaseName: podinfo-dev
  values:
    image: bzon/podinfo:master-z8oyahv0
    replicaCount: 1
    hpa:
      enabled: false
